### ISSUE TITLE
Browser coverage needs to be checked like Array#some.

### ISSUE THREAD

**Issue by mixed** [naver/egjs-imready#13]
## Description
It is necessary to use a polyfill according to the browser coverage or use an alternative method.

**Comment by daybrush** [comment]
@mixed 


|Internet Explorer|Chrome|Firefox|Safari|iOS|Android|
|---|---|---|---|---|---|
|9+(polyfill 8+)|Latest|Latest|Latest|7+|4+(polyfill 2.2+)|

### **Use polyfill if you want to use it in a lower version browser.**
   * Array.prototype.forEach
   * Array.prototype.map
   * Array.prototype.some
   * Array.prototype.filter
